### ISSUE TITLE
ImageColorAt out of bounds

### ISSUE THREAD

**Issue by 4dr1en** [xwiz/phash#4]
Hello, I also have a problem with *ImageColorAt*, with images in portrait format.
This is an example of an image that makes a lot of errors "*ImageColorAt out of bounds*": [https://imgur.com/a/7RBwF4k](https://imgur.com/a/7RBwF4k)
I use the code in wamp (php7.3.12).
Have you found a solution to this problem?

**Comment by xwiz** [comment]
This may be a problem with php mime configuration.

Take a look at this https://github.com/xwiz/phash/issues/3#issuecomment-577619625

**Comment by 4dr1en** [comment]
I don't know how to configure this but I think i found a problem in *makeThumbnail*.

this function make too small thumbail if the image is in portrait format.
I replaced 
```
$newheight = $thumbheight;

$divisor = $height / $thumbheight;

$newwidth = floor( $width / $divisor );
```

by
```
if($width >= $height){

            $newheight = $thumbheight;

            $divisor = $height / $thumbheight;

            $newwidth = floor( $width / $divisor );

        }

        else{

            $newwidth = $thumbwidth;

            $divisor = $width / $thumbwidth;

            $newheight = floor( $height / $divisor );

        }
```

And now that work for me. 👍

**Comment by xwiz** [comment]
Interesting can you share a sample problematic image? The resizing should normally be able to resize/downscale to 8 x 8 unless the images are smaller than that..

**Comment by 4dr1en** [comment]
I had this issue with all images with $height > $width. Even the images with just a 90° rotation.

**Comment by xwiz** [comment]
Hmm, been long I tested, will check it out and set up a unit test... Feel free to create PR if you have tested
